// Only keeping IDs for reference of what exists in the database
export const appointmentStatusIds: string[] = ['Can', 'Exp', 'Inv', 'NotExp', 'Pln'];

export const customColorIds: string[] = ['Cancelled', 'Exported', 'Invoiced', 'NotExported', 'OtherHours', 'Planned'];

export const dogSizeIds: string[] = ['L', 'M', 'S', 'X'];

export const hourTypeIds: string[] = ['Adm', 'App', 'Cur', 'Fac', 'Ink', 'Reis', 'sch', 'Stage', 'Vak', 'Zk'];

export const importExportTypeIds: string[] = ['Hour', 'Invoice', 'Purchase', 'Relation'];

// export const travelTimeTypeIds: string[] = ['HomeWork', 'WorkHome'];

export const serviceIds: string[] = ['trimmen', 'nagels_knippen', 'puppy_beurt'];

export const dogBreedIds: string[] = [
    'affenpinscher', 'afghaanse_windhond', 'aidi', 'airedale_terrier', 'akita', 'alaska_malamute',
    'alpenlandische_dachsbracke', 'american_akita', 'american_foxhound', 'american_staffordshire_terrier',
    'amerikaanse_cocker_spaniel', 'amerikaanse_water_spaniel', 'anglo_francais_de_petite_venerie',
    'appenzeller_sennenhond', 'argentijnse_dog', 'ariegois', 'australian_cattle_dog', 'australian_kelpie',
    'australian_shepherd', 'australian_silky_terrier', 'australian_stumpy_tail_cattle_dog', 'australian_terrier',
    'azawakh', 'barbet', 'barsoi', 'basenji', 'basset_artesien_normand', 'basset_bleu_de_gascogne',
    'basset_fauve_de_bretagne', 'basset_hound', 'bayerischer_gebirgsschweisshund', 'beagle', 'beagle_harrier',
    'bearded_collie', 'beauceron', 'bedlington_terrier', 'belgische_herdershond_groenendaeler',
    'belgische_herdershond_laekense', 'belgische_herdershond_mechelse', 'belgische_herdershond_tervuerense',
    'bergamasco', 'berghond_van_de_maremmen', 'berner_laufhund', 'berner_niederlaufhund', 'berner_sennenhond',
    'bichon_frise', 'billy', 'black_and_tan_coonhound', 'bloedhond', 'bolognezer', 'bordeaux_dog', 'border_collie',
    'border_terrier', 'bosnian_ostrodlaki_gonic_barak', 'boston_terrier', 'bouvier_des_ardennes',
    'bouvier_des_flandres', 'boxer', 'bracco_italiano', 'brandlbracke', 'braque_dauvergne', 'braque_de_lariege',
    'braque_du_bourbonnais', 'braque_francais_type_gascogne', 'braque_francais_type_pyrenees',
    'braque_saint_germain', 'braziliaanse_terrier', 'briard', 'briquet_griffon_vendeen', 'broholmer',
    'bull_terrier', 'bullmastiff', 'cairn_terrier', 'canaanhond', 'cane_corso', 'cao_da_serra_da_estrela_korthaar',
    'cao_da_serra_da_estrela_langhaar', 'cao_da_serra_de_aires', 'cao_de_agua_portugues',
    'cao_de_castro_laboreiro', 'cao_de_gado_transmontano', 'cao_fila_de_sao_miguel',
    'cavalier_king_charles_spaniel', 'centraal_aziatische_ovcharka', 'cesky_fousek', 'cesky_terrier',
    'chart_polski', 'chesapeake_bay_retriever', 'chien_dartois', 'chihuahua_korthaar', 'chihuahua_langhaar',
    'chinese_naakthond', 'chodsky_pes', 'chow_chow', 'cimarron_uruguayo', 'ciobanese_romanesc_carpatin',
    'ciobanesc_romanesc_de_bucovina', 'ciobanesc_romanesc_mioritic', 'cirneco_delletna', 'clumber_spaniel',
    'continental_bulldog', 'coton_de_tulear', 'crnogorski_planinski_gonic', 'curly_coated_retriever',
    'dalmatische_hond', 'dandie_dinmont_terrier', 'dashond_korthaar', 'dashond_langhaar', 'dashond_ruwhaar',
    'deens_zweedse_boerderijhond', 'deerhound', 'dobermann', 'drentsche_patrijshond', 'drever', 'duitse_brak',
    'duitse_dog_blauw', 'duitse_dog_geel_gestroomd', 'duitse_dog_zwart_zwart_wit', 'duitse_dwergpinscher',
    'duitse_herdershond_langstockhaar', 'duitse_herdershond_stokhaar', 'duitse_jachtterrier', 'duitse_pinscher',
    'duitse_staande_hond_draadhaar', 'duitse_staande_hond_korthaar', 'duitse_staande_hond_langhaar',
    'duitse_staande_hond_stekelhaar', 'duitse_wachtelhond', 'dunker', 'dwergdashond_korthaar',
    'dwergdashond_langhaar', 'dwergdashond_ruwhaar', 'dwergkeeshond', 'dwergpoedel',
    'dwergpoedel_grijs_abrikoos_rood', 'dwergschnauzer_peper_en_zout', 'dwergschnauzer_wit',
    'dwergschnauzer_zwart', 'dwergschnauzer_zwart_zilver', 'eesti_hagijas', 'engelse_bulldog',
    'engelse_cocker_spaniel', 'engelse_setter', 'engelse_springer_spaniel', 'engelse_toy_terrier',
    'english_foxhound', 'entlebucher_sennenhond', 'epagneul_bleu_de_picardie', 'epagneul_breton',
    'epagneul_de_pont_audemer', 'epagneul_francais', 'epagneul_nain_continental_papillon',
    'epagneul_nain_continental_phalene', 'epagneul_picard', 'erdelyi_kopo', 'eurasier', 'field_spaniel',
    'fila_brasileiro', 'finse_brak', 'finse_lappenhond', 'finse_spits', 'flatcoated_retriever',
    'foxterrier_draadhaar', 'foxterrier_gladhaar', 'francais_blanc_et_noir', 'francais_blanc_et_orange',
    'francais_tricolore', 'franse_bulldog', 'galgo_espanol', 'gammel_dansk_honsehund', 'golden_retriever',
    'gonczy_polski', 'gordon_setter', 'gos_datura_catala', 'grand_anglo_francais_blanc_et_noir',
    'grand_anglo_francais_blanc_et_orange', 'grand_anglo_francais_tricolore', 'grand_basset_griffon_vendeen',
    'grand_bleu_de_gascogne', 'grand_gascon_saintongeois', 'grand_griffon_vendeen', 'greyhound',
    'griffon_belge', 'griffon_bleu_de_gascogne', 'griffon_bruxellois', 'griffon_fauve_de_bretagne',
    'griffon_korthals', 'griffon_nivernais', 'groenlandhond', 'grote_keeshond_bruin_zwart',
    'grote_keeshond_wit', 'grote_keeshond_wolfsgrijs', 'grote_munsterlander', 'grote_poedel',
    'grote_poedel_grijs_abrikoos_rood', 'grote_zwitserse_sennenhond', 'haldenstovare', 'hamiltonstovare',
    'hannoverscher_schweisshund', 'harrier', 'havanezer', 'heidewachtel', 'hellinikos_ichnilatis',
    'hokkaido', 'hollandse_herdershond_korthaar', 'hollandse_herdershond_langhaar',
    'hollandse_herdershond_ruwhaar', 'hollandse_smoushond', 'hovawart', 'hrvatski_ovcar', 'hygenhund',
    'ierse_rood_witte_setter', 'ierse_setter', 'ierse_terrier', 'ierse_water_spaniel', 'ierse_wolfshond',
    'ijslandse_hond', 'irish_glen_of_imaal_terrier', 'irish_soft_coated_wheaten_terrier',
    'istarski_kratkodiaki_gonic', 'istarski_ostrodlaki_gonic', 'italiaans_windhondje', 'jack_russell_terrier',
    'jamthund', 'japanse_spaniel', 'japanse_spits', 'japanse_terrier', 'jura_laufhund', 'jura_niederlaufhund',
    'kai', 'kangal_kopek', 'kaninchen_dashond_korthaar', 'kaninchen_dashond_langhaar',
    'kaninchen_dashond_ruwhaar', 'karelische_berenhond', 'kaukasische_ovcharka', 'kerry_blue_terrier',
    'king_charles_spaniel', 'kintamani_bali_dog', 'kishu', 'komondor', 'korea_jindo_dog', 'kraski_ovcar',
    'kromfohrländer', 'kuvasz', 'labrador_retriever', 'lagotto_romagnolo', 'lakeland_terrier', 'landseer',
    'lapinporokoira', 'lhasa_apso', 'lurcher', 'luzerner_laufhund', 'maltese', 'manchester_terrier',
    'maremma_en_abruzzese', 'markiesje', 'mastiff', 'mastin_del_pirineo', 'mastin_espanol',
    'mastino_napoletano', 'mini_american_shepherd', 'miniatuur_bull_terrier', 'miniatuur_pinscher',
    'miniatuur_poedel', 'miniatuur_schnauzer', 'montenegrijnse_berghond', 'mops', 'mudi',
    'nederlandse_kooikerhondje', 'nederlandse_schapendoes', 'newfoundland', 'norfolk_terrier',
    'noorse_buhund', 'noorse_elandhond_grijs', 'noorse_elandhond_zwart', 'noorse_lundehund',
    'norwich_terrier', 'oost_siberische_laika', 'oosterse_spits', 'otterhound', 'parson_russell_terrier',
    'perdigueiro_portugues', 'perro_de_agua_espanol', 'perro_de_presa_canario',
    'petit_basset_griffon_vendeen', 'petit_bleu_de_gascogne', 'petit_brabancon', 'pharaohond', 'picardy',
    'podenco_canario', 'podenco_ibicenco', 'podengo_portugues', 'poedelpointer', 'pointer',
    'polski_owczarek_nizinny', 'polski_owczarek_podhalanski', 'portugese_podengo', 'prazsky_krysarik',
    'puli', 'pumi', 'pyreneese_berghond', 'pyreneese_herdershond', 'rafeiro_do_alentejo',
    'rhodesian_ridgeback', 'rottweiler', 'russische_zwarte_terrier', 'russkiy_toy', 'saarlooswolfhond',
    'saluki', 'samojeed', 'schillerstovare', 'schotse_herdershond_korthaar', 'schotse_herdershond_langhaar',
    'schotse_terrier', 'sealyham_terrier', 'shar_pei', 'shiba_inu', 'shih_tzu', 'siberische_husky',
    'silky_terrier', 'sloughi', 'slovensky_cuvac', 'slovensky_kopov', 'smalandsstovare',
    'soft_coated_wheaten_terrier', 'spaniel_van_pont_audemer', 'spaanse_mastiff', 'spaanse_waterhond',
    'spinone_italiano', 'srpski_gonic', 'srpski_trobojni_gonic', 'stabijhoun', 'staffordshire_bull_terrier',
    'sussex_spaniel', 'taigan', 'tatrahond', 'tervuerense_herdershond', 'thai_ridgeback',
    'tibetaanse_mastiff', 'tibetaanse_spaniel', 'tibetaanse_terrier', 'toy_poedel', 'vizsla_draadhaar',
    'vizsla_korthaar', 'volpino_italiano', 'weimaraner', 'welsh_corgi_cardigan', 'welsh_corgi_pembroke',
    'welsh_springer_spaniel', 'welsh_terrier', 'west_highland_white_terrier', 'west_siberische_laika',
    'whippet', 'wetterhoun', 'yorkshire_terrier', 'zuid_russische_ovcharka', 'zwart_russische_terrier',
    'zweedse_lappenhond', 'zwitserse_witte_herdershond'
]; 