name: API Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.11
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: 4Loki_db
          TZ: UTC
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mariadb-admin ping -h localhost -uroot -proot"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5
          --health-start-period=20s

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Set database timezone
      run: mysql -h127.0.0.1 -P3306 -uroot -proot -e "SET GLOBAL time_zone = '+00:00';"

    - name: Initialize database
      run: |
        mysql -h127.0.0.1 -P3306 -uroot -proot 4Loki_db < 01-init.sql

    - name: Run tests
      run: npm test
      env:
        DB_HOST: 127.0.0.1
        DB_USER: root
        DB_PASSWORD: root
        DB_DATABASE: 4Loki_db
        NODE_ENV: test
        TZ: UTC
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          coverage/
          test-results/ 