name: API Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Add permissions for the test reporter
permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm install
      timeout-minutes: 5

    - name: Run tests
      run: npm test
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3307
        DB_USER: root
        DB_PASSWORD: root
        DB_DATABASE: 4Loki_db
        NODE_ENV: test
        TZ: UTC
      timeout-minutes: 5

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Jest Tests            # Name of the check run which will be created
        path: test-results/junit.xml # Path to test results
        reporter: jest-junit        # Format of test results

    - name: Display test summary
      if: always()
      run: |
        echo "Test Execution Summary"
        echo "===================="
        if [ -f test-results/junit.xml ]; then
          cat test-results/junit.xml
        fi
        if [ -d coverage ]; then
          echo -e "\nCoverage Summary"
          echo "================"
          cat coverage/coverage-summary.json || true
        fi
      timeout-minutes: 1
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          coverage/
          test-results/
      timeout-minutes: 2 